[package]
name = "wgmetrics"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
axum = "0.6"
clap = { version = "4", features = ["derive"] }
serde_json = "1"
sudo = "0.6"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
wglib = { path = "../wglib" }
