[package]
name = "wglib"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
base64 = "0.21"
crypto_box = "0.8"
ipnet = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
